### ISSUE TITLE
Request: When disassembling MIPS binaries, scan gp register accesses to detect more file splits in sdata

### ISSUE THREAD

**Issue by ChrisNonyminus** [Decompollaborate/spimdisasm#106]
In MIPS, sdata/sbss/scommon variables in the same c file as the function they're accessed by are accessed via a gp register-relative load/store instead of a standard lui->(s/l)(w/h/b)(u) combo.

When splat is ran on a MIPS binary, it should check for these instances and notify the user about this and tell the address the variable resides in.

I.E:

```
In the section "sdata", variable foo, at address 0x80098000, may belong to 
the source file bar.c, as it's accessed by one of bar.c's functions (bar_sub_0) 
via a single lw instruction using a gp-relative offset.
```

A yaml option for this would be good, something like "scan_sdata_splits".

**Comment by ChrisNonyminus** [comment]
> Do you have a concrete test case for this?

For [mml1](https://github.com/ChrisNonyminus/mml1), I found that Moji_flag, at address 80098A58, was being used via gp-relative offset load/stores in moji.c, and only moji.c (other accesses of Moji_flag, from other c files, use the standard lui method). (moji.c is located at approximately 80053788-8005497C.

**Comment by ChrisNonyminus** [comment]
Also, the inverse could probably be done, where variables in split small-data sections could be scanned for all gp-relative accesses in an unsplit text section, and report possible splits in the text section.

**Comment by AngheloAlf** [comment]
Different compilers (and compiler versions) have different behavior about this, meaning it isn't a good way to detect file splits on sdata/sbss sections.
