### ISSUE TITLE
Support `bal`

### ISSUE THREAD

**Issue by EllipticEllipsis** [Decompollaborate/spimdisasm#14]
As the pseudoinstruction corresponding to `bgezal      $zero`

**Comment by AngheloAlf** [comment]
We should probably move this issue to https://github.com/Decompollaborate/rabbitizer

**Comment by AngheloAlf** [comment]
Addressed in https://github.com/Decompollaborate/rabbitizer/commit/15b254bf036b5347b7c16b848dd75fa301cc4cd3
