### ISSUE TITLE
[Suggestion]: Add Mips Debug .Mdebug symbols support

### ISSUE THREAD

**Issue by weirdbeardgame** [Decompollaborate/spimdisasm#159]
### Explain the feature

- Add support for .Mdebug symbols found in PS2 games like Fatal Frame

### Advantage

- MDebug has more detail then the ELF symbol table revealing more functions than the ELF Symbol table.

- There's more detail about Symbols and Structs in PS2 MDebug as well

### Example(s)

https://github.com/weirdbeardgame/Fatal-Frame-2/blob/main/Documentation/Types.h - An example of MDebug symbols read from a Tool called CCC created by ChaoticGD

Or his excellent implementation of CCC included in his Ghidra plugin - https://github.com/chaoticgd/ghidra-emotionengine-reloaded

**Comment by AngheloAlf** [comment]
I'm not sure mdebug parsing may bring much value to spimdisasm.

- Sadly mdebug isn't very standarized and poorly documented, so parsing it is a headache.
- From all the stuff mdebug may have, only symbol names and sizes are useful for disassembly.

My recommendation is to use an external tool to parse the mdebug section and generate a symbol_addrs file that spimdisasm can understand.
This tool can parse some flavor of mdebug, you could try to adapt it to generate a symbol_addrs file: https://github.com/decompals/ultralib/blob/main/tools/libelf.py
