### ISSUE TITLE
[Suggestion]: Ability to specify per-symbol visibility 

### ISSUE THREAD

**Issue by ethteck** [Decompollaborate/spimdisasm#164]
### Explain the feature

It'd be nice if symbols could be configured as not always global so the emitted asm changes the visibility of the symbol.

### Advantage

It'd help with C++ projects

### Disadvantage

More configuration to support
If things from the same TU aren't all properly migrated, there could be undefined symbol problems

### Example(s)

Thanks encounter for this macro from dtk: https://github.com/encounter/decomp-toolkit/blob/main/assets/macros.inc#L188

I forgot how the spimdisasm symbol config looks, so forgive me for using splat symbol_addrs:

thing = 0x1230; visibility:weak

then instead of `glabel thing`
we have `glabel thing, weak`

which expands to `visibility=weak`

**Comment by AngheloAlf** [comment]
dun
