### ISSUE TITLE
[Frug]: Missing unreferenced RODATA symbols in function using migrate_rodata_to_functions: True

### ISSUE THREAD

**Issue by Ryan-Myers** [Decompollaborate/spimdisasm#172]
### Explain the problem.

So Diddy Kong Racing has a function where there's a few RODATA symbols that are supposed to be part of a specific function, but got optimized out by the compiler. So the symbols are still there, and they're required to match, but the function itself doesn't reference these symbols. This makes spim ignore them when using `migrate_rodata_to_functions: True`. 

If I manually add the missing RODATA symbols into the file, I get a matching build. So it's the only thing preventing me from having a matching build for DKR.

I've tried several things to get it to generate the symbols including defining them with `force_migration:True` in the symbol file, with no luck.

Here's what is generated:
![image](https://github.com/user-attachments/assets/155956d4-9684-467d-a50f-9da7795d3fce)

And here's what is *should* look like to match:
![image](https://github.com/user-attachments/assets/dcde3ec5-a9b9-46d8-b31f-7de481478802)

Here's me trying to force the symbols:
![image](https://github.com/user-attachments/assets/d51fbe2c-2fc9-4712-9635-e24a29fcf2d0)

and here's the error message given from splat:
![image](https://github.com/user-attachments/assets/ec99f112-c8fb-4e5c-aae5-938d9232247c)

### Reproducer

https://github.com/Ryan-Myers/Racing_Splat

### spimdisasm version

1.28.1

### Optional: splat version

0.27.0

**Comment by AngheloAlf** [comment]
Fixed on release [`1.30.0`](https://github.com/Decompollaborate/spimdisasm/releases/tag/1.30.0). Commit 9593eb7ab875d5c44989f810dbb0e08c5560bd41
