### ISSUE TITLE
unhashable type using python 3.10.7 trying to compile pokestadium repo

### ISSUE THREAD

**Issue by SillyLily1313** [Decompollaborate/spimdisasm#55]
File "/usr/local/lib/python3.10/dist-packages/spimdisasm/mips/symbols/MipsSymbolFunction.py", line 173, in analyze
    funcSym.referenceFunctions.add(self.contextSym)
TypeError: unhashable type: 'ContextSymbol'
make: *** [Makefile:74: split] Error 1

is there a required python version to use or is there plans to update to work with newer versions

**Comment by AngheloAlf** [comment]
I released a new version (1.6.2) which in my local testing fixed the issue, could you confirm if it fixes the issue for you too?
You should be able to install it with either of this two commands:
```
pip install spimdisasm -U
```
```
pip install spimdisasm==1.6.2
```

**Comment by SillyLily1313** [comment]
`pip install spimdisasm==1.6.0`

that did work with the pokestadium repo! :) 

I also tried the newer versions you suggested, but they seem to not resolve the issue yet so newer versions and possible certain older versions break functionality. would be something to look into for sure.

**Comment by AngheloAlf** [comment]
I'm not able to reproduce the problem with 1.6.3, I just tested 1.6.3 on pokemon stadium and it seems to work fine

**Comment by SillyLily1313** [comment]
1.6.3 now works i verified as well. very interesting! i dont know what could have caused that to be honest maybe the environment didnt update properly after switched versions all i can think of. but it seems to be resolved now!

**Comment by AngheloAlf** [comment]
Happy to hear that!

**Comment by SillyLily1313** [comment]
thank you for responding so fast and being active! always good to see and very helpful too!
