### ISSUE TITLE
Some strings not getting detected

### ISSUE THREAD

**Issue by simonlindholm** [Decompollaborate/spimdisasm#59]
I'm looking at IDO 5.3 ugen right now, and some strings aren't getting detected as they should. The .text references a string like so:
```
/* 05034C 0045034C 8F8D8068 */  lw          $t5, %got(D_1000DA23)($gp)
/* 050350 00450350 8F998028 */  lw          $t9, %got(func_0044F58C)($gp)
/* 050354 00450354 25ADDA23 */  addiu       $t5, $t5, %lo(D_1000DA23)
```
but the symbol D_1000DA23 is never emitted; it's supposed to be in the middle of some chunk of .word's:
```
glabel RO_1000D570
/* 07A570 1000D570 7567656E */ .word 0x7567656E
/* 07A574 1000D574 3A43616E */ .word 0x3A43616E
...
/* 07AA20 1000DA20 2020202D */ .word 0x2020202D
/* 07AA24 1000DA24 66703332 */ .word 0x66703332
/* 07AA28 1000DA28 72656773 */ .word 0x72656773
```

This is probably related to lack of nul termination and the memory address being unaligned, and it's fair to say that detecting and generating `.asci` strings for this isn't very important. *But*, it feels like a bug that the symbol D_1000DA23 points to nothing, and it would be useful to me if a label was inserted at the right spot.

**Comment by EllipticEllipsis** [comment]
Also happens for arrays of strings in .data: from `cfe`,
```
glabel type_name
/* 0BD478 1001D478 */ .word 0x1000A5B0
/* 0BD47C 1001D47C */ .word 0x1000A5B8
/* 0BD480 1001D480 */ .word 0x1000A5C0
/* 0BD484 1001D484 */ .word 0x1000A5CC
/* 0BD488 1001D488 */ .word 0x1000A5D4
[...]
```
which points to
```
ident
double
long double
float
label
char
long
long long
short
signed
unsigned
unsigned char
unsigned int
unsigned long
unsigned long long
unsigned short
void
any type
array
enum
function
pointer
reference
struct
```

**Comment by AngheloAlf** [comment]
The latest changes to rodata disassembly seems to have fixed those symbols not being emitted.
```mips
glabel D_1000DA03
/* 07AA03 1000DA03 */ .byte 0x2D
/* 07AA04 1000DA04 6E6F6F66 */ .word 0x6E6F6F66
/* 07AA08 1000DA08 66736574 */ .word 0x66736574
/* 07AA0C 1000DA0C 6F707420 */ .word 0x6F707420
/* 07AA10 1000DA10 20202020 */ .word 0x20202020
/* 07AA14 1000DA14 20202020 */ .word 0x20202020
/* 07AA18 1000DA18 20202020 */ .word 0x20202020
/* 07AA1C 1000DA1C 20202020 */ .word 0x20202020
/* 07AA20 1000DA20 */ .byte 0x20
/* 07AA21 1000DA21 */ .byte 0x20
/* 07AA22 1000DA22 */ .byte 0x20

glabel D_1000DA23
/* 07AA23 1000DA23 */ .byte 0x2D
/* 07AA24 1000DA24 66703332 */ .word 0x66703332
/* 07AA28 1000DA28 72656773 */ .word 0x72656773
```
This change is currently still in the develop branch.

Detecting strings without nul termination is much more trickier tho, not sure how we can implement this

**Comment by simonlindholm** [comment]
Nice! I added a m2c flag --heuristic-strings as a work-around for reading those as strings, which works well enough for me.
